[package]
name = "aima-rust"
version = "0.1.0"
authors = ["nconnor <nicholas.k.connor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[badges]

